<p>Welcome to Be Beautiful Salon! Please choose a stylist for more information!</p>

<aside>
        <h2>Login here!</h2>
        <form action="?" method="POST">
            <label for="username">Username:</label>
                <input type="text" name="username" id="username" maxlength="20" size="20" /><br/>
            <label for="password">Password:</label>
                <input type="password" name="password" id="password" maxlength="20" size="20" /><br/>
            <input type="submit" />
        </form>
    </aside>

<?php

?>
